export const doctorSidebarOptions = [
  { name: "Dashboard", href: "dashboard" },
  { name: "Requests", href: "requests" },
  { name: "My Appointments", href: "my-appointments" },
  { name: "Available Timings", href: "available-timings" },
  { name: "My Patients", href: "my-patients" },
  { name: "Specialties & Services", href: "specialties-services" },
  { name: "Reviews", href: "reviews" },
  { name: "Accounts", href: "accounts" },
  { name: "Invoices", href: "invoices" },
  { name: "Payout Settings", href: "payout-settings" },
  { name: "Messages", href: "messages" },
  { name: "Profile Settings", href: "profile-settings" },
  { name: "Social Media", href: "social-media" },
  { name: "Change Password", href: "change-password" },
  { name: "Logout", href: "/" },
];
