import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import MainMenu from "@/components/header/MainMenu";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "600"], // You can specify the font weights you need
});

export const metadata: Metadata = {
  title: "Decure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className}  `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainMenu />
          <main className="max-w-7xl mx-auto mt-20">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
